### ISSUE TITLE
Failover timeout

### ISSUE THREAD

**Issue by Jasim9** [bmuller/txyam#10]
I want to know what dead_timeout does the client use by default and is there a way to pass it as a parameter? I was checking the failover and when I bring a failed server backup, I think it takes quite a while for YamClient to start bringing stats from that server.

**Comment by Jasim9** [comment]
Okay wait, I checked, it detects as soon as it comes up, there is some other problem may be in my stat calculation function.

**Comment by bmuller** [comment]
That's all controlled by [twisted.internet.protocol.ReconnectingClientFactory](http://twistedmatrix.com/documents/current/api/twisted.internet.protocol.ReconnectingClientFactory.html).  There's an exponential back off for retries.

**Comment by Jasim9** [comment]
Is there a way to expose the `resetDelay` function from `ReconnectingClientFactory` in txyam so that we can control the delay between retries within the application?

**Comment by bmuller** [comment]
Each of your client's factories (in the `factories` property) is an instance of `MemCacheClientFactory` which extends `ReconnectingClientFactory`.  This means that you can do something like:

``` python
for factory in client.factories:
     factory.resetDelay() 
```

though I'm not sure why that's necessary.  Why do you need to reset the delay?

**Comment by Jasim9** [comment]
It can be useful for implementing a custom timeout if we don't want to use exponential back off. I want a constant timeout of 60 seconds for example, so every 60 seconds I can invoke the `resetDelay()` and the client will try to reconnect.
